import { TestIR, TestIRStep, FrameworkType, GeneratedCodeFile } from '../types/testAutomation';

export function generateAutomationSuite(ir: TestIR, framework: FrameworkType): GeneratedCodeFile[] {
  switch (framework) {
    case 'playwright-ts':
      return generatePlaywrightTS(ir);
    case 'playwright-python':
      return generatePlaywrightPython(ir);
    case 'selenium-java':
      return generateSeleniumJava(ir);
    case 'selenium-python':
      return generateSeleniumPython(ir);
    default:
      return generatePlaywrightTS(ir);
  }
}

/**
 * Clean sanitization for identifier names
 */
function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
}

function toCamelCase(str: string): string {
  const p = toPascalCase(str);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

// -------------------------------------------------------------
// Playwright TypeScript Generator (Page Object Model Pattern)
// -------------------------------------------------------------
function generatePlaywrightTS(ir: TestIR): GeneratedCodeFile[] {
  const pageClassName = `${toPascalCase(ir.feature || 'App')}Page`;
  const specFileName = `${(ir.testCaseId || 'test').toLowerCase()}_${toCamelCase(ir.title)}.spec.ts`;

  // Page Object Class
  let pageObjectMethods = '';
  const distinctTargets = new Map<string, { semantic: string; locator: string }>();

  ir.steps.forEach((step: TestIRStep) => {
    if (step.target?.semantic && step.target.recommendedLocator) {
      const key = toCamelCase(step.target.semantic);
      if (!distinctTargets.has(key)) {
        distinctTargets.set(key, {
          semantic: step.target.semantic,
          locator: step.target.recommendedLocator
        });
      }
    }
  });

  distinctTargets.forEach((target, key) => {
    pageObjectMethods += `
  /** ${target.semantic} */
  get ${key}() {
    return this.page.locator(${JSON.stringify(target.locator)});
  }
`;
  });

  const pageObjectCode = `import { Page, expect } from '@playwright/test';

/**
 * Page Object Model for ${ir.feature}
 * Auto-generated by AutoTest Architect from Test IR: ${ir.testCaseId}
 */
export class ${pageClassName} {
  readonly page: Page;

  constructor(page: Page) {
    this.page = page;
  }

  async goto(url = ${JSON.stringify(ir.baseUrl || '/')}) {
    await this.page.goto(url);
  }
${pageObjectMethods}
}
`;

  // Spec file
  let testStepsCode = '';
  ir.steps.forEach((step: TestIRStep) => {
    testStepsCode += `    // Step ${step.stepNumber}: ${step.description}\n`;
    if (step.action === 'navigate') {
      testStepsCode += `    await appPage.goto(${JSON.stringify(step.value || ir.baseUrl || '/')});\n`;
    } else if (step.action === 'fill' && step.target) {
      const targetName = toCamelCase(step.target.semantic);
      testStepsCode += `    await appPage.${targetName}.fill(${JSON.stringify(step.value || '')});\n`;
    } else if (step.action === 'click' && step.target) {
      const targetName = toCamelCase(step.target.semantic);
      testStepsCode += `    await appPage.${targetName}.click();\n`;
    } else if (step.action === 'assert_visible' && step.target) {
      const targetName = toCamelCase(step.target.semantic);
      testStepsCode += `    await expect(appPage.${targetName}).toBeVisible();\n`;
    } else if (step.action === 'assert_text' && step.target) {
      const targetName = toCamelCase(step.target.semantic);
      testStepsCode += `    await expect(appPage.${targetName}).toContainText(${JSON.stringify(step.expectedResult || step.value || '')});\n`;
    } else if (step.action === 'assert_url') {
      testStepsCode += `    await expect(page).toHaveURL(new RegExp(${JSON.stringify(step.value || '')}));\n`;
    } else if (step.action === 'select' && step.target) {
      const targetName = toCamelCase(step.target.semantic);
      testStepsCode += `    await appPage.${targetName}.selectOption(${JSON.stringify(step.value || '')});\n`;
    } else if (step.action === 'check' && step.target) {
      const targetName = toCamelCase(step.target.semantic);
      testStepsCode += `    await appPage.${targetName}.check();\n`;
    } else {
      testStepsCode += `    // Custom action: ${step.action}\n`;
    }
    testStepsCode += `\n`;
  });

  const specCode = `import { test, expect } from '@playwright/test';
import { ${pageClassName} } from '../pages/${pageClassName}';

test.describe('${ir.feature}: ${ir.title}', () => {
  let appPage: ${pageClassName};

  test.beforeEach(async ({ page }) => {
    appPage = new ${pageClassName}(page);
  });

  test('${ir.testCaseId} - ${ir.title.replace(/'/g, "\\'")}', async ({ page }) => {
${testStepsCode}  });
});
`;

  const configCode = `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['html'], ['json', { outputFile: 'test-results.json' }]],
  use: {
    baseURL: '${ir.baseUrl || 'https://app.example.com'}',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
  ],
});
`;

  return [
    {
      filename: specFileName,
      filepath: `tests/${specFileName}`,
      language: 'typescript',
      framework: 'playwright-ts',
      code: specCode,
      description: 'Playwright E2E Test Specification'
    },
    {
      filename: `${pageClassName}.ts`,
      filepath: `pages/${pageClassName}.ts`,
      language: 'typescript',
      framework: 'playwright-ts',
      code: pageObjectCode,
      description: 'Page Object Model element mappings and actions'
    },
    {
      filename: 'playwright.config.ts',
      filepath: 'playwright.config.ts',
      language: 'typescript',
      framework: 'playwright-ts',
      code: configCode,
      description: 'Playwright runner configuration & test harness'
    }
  ];
}

// -------------------------------------------------------------
// Playwright Python Generator (Pytest + Playwright)
// -------------------------------------------------------------
function generatePlaywrightPython(ir: TestIR): GeneratedCodeFile[] {
  const pageClassName = `${toPascalCase(ir.feature || 'App')}Page`;
  const snakeFeature = (ir.feature || 'app').toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const testFileName = `test_${(ir.testCaseId || 'test').toLowerCase()}_${snakeFeature}.py`;

  let pageMethods = '';
  ir.steps.forEach((step: TestIRStep) => {
    if (step.target?.semantic && step.target.recommendedLocator) {
      const funcName = step.target.semantic.toLowerCase().replace(/[^a-z0-9]+/g, '_');
      pageMethods += `
    @property
    def ${funcName}(self):
        return self.page.locator(${JSON.stringify(step.target.recommendedLocator)})
`;
    }
  });

  const pageObjectCode = `from urllib.parse import urljoin
from playwright.sync_api import Page, expect

class ${pageClassName}:
    def __init__(self, page: Page):
        self.page = page
        self.base_url = "${ir.baseUrl || '/'}"

    def navigate(self, url=None):
        self.page.goto(urljoin(self.base_url.rstrip('/') + '/', url or ''))
${pageMethods}
`;

  let testSteps = '';
  ir.steps.forEach((step: TestIRStep) => {
    testSteps += `    # Step ${step.stepNumber}: ${step.description}\n`;
    if (step.action === 'navigate') {
      testSteps += `    app_page.navigate(${JSON.stringify(step.value || ir.baseUrl || '/')})\n`;
    } else if (step.action === 'fill' && step.target) {
      const targetName = step.target.semantic.toLowerCase().replace(/[^a-z0-9]+/g, '_');
      testSteps += `    app_page.${targetName}.fill(${JSON.stringify(step.value || '')})\n`;
    } else if (step.action === 'click' && step.target) {
      const targetName = step.target.semantic.toLowerCase().replace(/[^a-z0-9]+/g, '_');
      testSteps += `    app_page.${targetName}.click()\n`;
    } else if (step.action === 'assert_visible' && step.target) {
      const targetName = step.target.semantic.toLowerCase().replace(/[^a-z0-9]+/g, '_');
      testSteps += `    expect(app_page.${targetName}).to_be_visible()\n`;
    } else if (step.action === 'assert_text' && step.target) {
      const targetName = step.target.semantic.toLowerCase().replace(/[^a-z0-9]+/g, '_');
      testSteps += `    expect(app_page.${targetName}).to_contain_text(${JSON.stringify(step.expectedResult || step.value || '')})\n`;
    }
    testSteps += `\n`;
  });

  const testFileCode = `import pytest
from playwright.sync_api import Page, expect
from pages.${pageClassName.toLowerCase()} import ${pageClassName}

def test_${(ir.testCaseId || 'test').toLowerCase()}_${toCamelCase(ir.title).toLowerCase()}(page: Page):
    """${ir.testCaseId}: ${ir.title}"""
    app_page = ${pageClassName}(page)

${testSteps}
`;

  return [
    {
      filename: testFileName,
      filepath: `tests/${testFileName}`,
      language: 'python',
      framework: 'playwright-python',
      code: testFileCode,
      description: 'PyTest Playwright automated test specification'
    },
    {
      filename: `${pageClassName.toLowerCase()}.py`,
      filepath: `pages/${pageClassName.toLowerCase()}.py`,
      language: 'python',
      framework: 'playwright-python',
      code: pageObjectCode,
      description: 'Python Page Object Class with unified selectors'
    }
  ];
}

// -------------------------------------------------------------
// Selenium Java Generator (Selenium 4 + TestNG)
// -------------------------------------------------------------
function generateSeleniumJava(ir: TestIR): GeneratedCodeFile[] {
  const pageClassName = `${toPascalCase(ir.feature || 'App')}Page`;
  const testClassName = `${toPascalCase(ir.testCaseId)}Test`;

  let webElements = '';
  ir.steps.forEach((step: TestIRStep) => {
    if (step.target?.semantic && step.target.recommendedLocator) {
      const varName = toCamelCase(step.target.semantic);
      const sel = step.target.recommendedLocator;
      let byClause = `By.cssSelector("${sel.replace(/"/g, '\\"')}")`;
      if (sel.startsWith('//') || sel.startsWith('(')) {
        byClause = `By.xpath("${sel.replace(/"/g, '\\"')}")`;
      }
      webElements += `
    public WebElement get${toPascalCase(step.target.semantic)}() {
        return driver.findElement(${byClause});
    }
`;
    }
  });

  const pageCode = `package com.autotest.pages;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

public class ${pageClassName} {
    private final WebDriver driver;
    private final String baseUrl = "${ir.baseUrl || 'https://app.example.com'}";

    public ${pageClassName}(WebDriver driver) {
        this.driver = driver;
    }

    public void navigateTo(String url) {
        String targetUrl = url == null || url.isBlank() ? baseUrl : url;
        if (!targetUrl.startsWith("http://") && !targetUrl.startsWith("https://")) {
            targetUrl = baseUrl.replaceAll("/+$", "") + (targetUrl.startsWith("/") ? targetUrl : "/" + targetUrl);
        }
        driver.get(targetUrl);
    }
${webElements}
}
`;

  let testSteps = '';
  ir.steps.forEach((step: TestIRStep) => {
    testSteps += `        // Step ${step.stepNumber}: ${step.description}\n`;
    if (step.action === 'navigate') {
      testSteps += `        page.navigateTo(${JSON.stringify(step.value || ir.baseUrl || '/')});\n`;
    } else if (step.action === 'fill' && step.target) {
      testSteps += `        page.get${toPascalCase(step.target.semantic)}().sendKeys("${(step.value || '').replace(/"/g, '\\"')}");\n`;
    } else if (step.action === 'click' && step.target) {
      testSteps += `        page.get${toPascalCase(step.target.semantic)}().click();\n`;
    } else if (step.action === 'assert_visible' && step.target) {
      testSteps += `        Assert.assertTrue(page.get${toPascalCase(step.target.semantic)}().isDisplayed(), "Element should be visible");\n`;
    } else if (step.action === 'assert_text' && step.target) {
      testSteps += `        Assert.assertTrue(page.get${toPascalCase(step.target.semantic)}().getText().contains("${(step.expectedResult || step.value || '').replace(/"/g, '\\"')}");\n`;
    }
    testSteps += `\n`;
  });

  const testCode = `package com.autotest.tests;

import com.autotest.pages.${pageClassName};
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class ${testClassName} {
    private WebDriver driver;
    private ${pageClassName} page;

    @BeforeMethod
    public void setUp() {
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        page = new ${pageClassName}(driver);
    }

    @Test(description = "${ir.testCaseId}: ${ir.title.replace(/"/g, '\\"')}")
    public void testExecution() {
${testSteps}    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }
}
`;

  return [
    {
      filename: `${testClassName}.java`,
      filepath: `src/test/java/com/autotest/tests/${testClassName}.java`,
      language: 'java',
      framework: 'selenium-java',
      code: testCode,
      description: 'Selenium 4 TestNG test suite'
    },
    {
      filename: `${pageClassName}.java`,
      filepath: `src/main/java/com/autotest/pages/${pageClassName}.java`,
      language: 'java',
      framework: 'selenium-java',
      code: pageCode,
      description: 'Selenium Page Object class'
    }
  ];
}

// -------------------------------------------------------------
// Selenium Python Generator
// -------------------------------------------------------------
function generateSeleniumPython(ir: TestIR): GeneratedCodeFile[] {
  const pageClassName = `${toPascalCase(ir.feature || 'App')}Page`;
  const testFileName = `test_selenium_${(ir.testCaseId || 'test').toLowerCase()}.py`;

  let elementMethods = '';
  ir.steps.forEach((step: TestIRStep) => {
    if (step.target?.semantic && step.target.recommendedLocator) {
      const funcName = step.target.semantic.toLowerCase().replace(/[^a-z0-9]+/g, '_');
      const sel = step.target.recommendedLocator;
      const byClause = sel.startsWith('//') ? `By.XPATH, "${sel}"` : `By.CSS_SELECTOR, "${sel}"`;
      elementMethods += `
    def get_${funcName}(self):
        return self.wait.until(EC.presence_of_element_located((${byClause})))
`;
    }
  });

  const pageCode = `from urllib.parse import urljoin
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class ${pageClassName}:
    def __init__(self, driver):
        self.driver = driver
        self.wait = WebDriverWait(driver, 10)
        self.url = "${ir.baseUrl || 'https://app.example.com'}"

    def open(self, url=None):
        self.driver.get(urljoin(self.url.rstrip('/') + '/', url or ''))
${elementMethods}
`;

  let testSteps = '';
  ir.steps.forEach((step: TestIRStep) => {
    testSteps += `    # Step ${step.stepNumber}: ${step.description}\n`;
    if (step.action === 'navigate') {
      testSteps += `    page.open(${JSON.stringify(step.value || ir.baseUrl || '/')})\n`;
    } else if (step.action === 'fill' && step.target) {
      const funcName = step.target.semantic.toLowerCase().replace(/[^a-z0-9]+/g, '_');
      testSteps += `    page.get_${funcName}().clear()\n`;
      testSteps += `    page.get_${funcName}().send_keys(${JSON.stringify(step.value || '')})\n`;
    } else if (step.action === 'click' && step.target) {
      const funcName = step.target.semantic.toLowerCase().replace(/[^a-z0-9]+/g, '_');
      testSteps += `    page.get_${funcName}().click()\n`;
    } else if (step.action === 'assert_visible' && step.target) {
      const funcName = step.target.semantic.toLowerCase().replace(/[^a-z0-9]+/g, '_');
      testSteps += `    assert page.get_${funcName}().is_displayed()\n`;
    }
    testSteps += `\n`;
  });

  const testCode = `import pytest
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from pages.${pageClassName.toLowerCase()} import ${pageClassName}

@pytest.fixture
def driver():
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_argument("--headless=new")
    d = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
    yield d
    d.quit()

def test_${(ir.testCaseId || 'test').toLowerCase()}(driver):
    """${ir.testCaseId}: ${ir.title}"""
    page = ${pageClassName}(driver)
${testSteps}
`;

  return [
    {
      filename: testFileName,
      filepath: `tests/${testFileName}`,
      language: 'python',
      framework: 'selenium-python',
      code: testCode,
      description: 'Selenium Python Pytest script'
    },
    {
      filename: `${pageClassName.toLowerCase()}.py`,
      filepath: `pages/${pageClassName.toLowerCase()}.py`,
      language: 'python',
      framework: 'selenium-python',
      code: pageCode,
      description: 'Selenium Page Object class'
    }
  ];
}
