import JSZip from 'jszip';
import { GeneratedCodeFile, FrameworkType, TestIR } from '../types/testAutomation';
import { generateCiPipeline } from './ciGenerators';

export async function exportSuiteAsZip(
  files: GeneratedCodeFile[],
  framework: FrameworkType,
  ir: TestIR
): Promise<void> {
  const zip = new JSZip();

  // Add the generated test and page object files
  files.forEach((file) => {
    zip.file(file.filepath, file.code);
  });

  // Include CI/CD pipeline inside the export package
  const ghWorkflow = generateCiPipeline('github-actions', framework, ir);
  zip.file(ghWorkflow.filepath, ghWorkflow.code);

  // Add a clean README.md explaining how to run
  let runCommand = 'npx playwright test';
  let installCommand = 'npm install && npx playwright install chromium';
  if (framework === 'playwright-python') {
    installCommand = 'pip install -r requirements.txt && playwright install';
    runCommand = 'pytest tests/';
  } else if (framework === 'selenium-java') {
    installCommand = 'Java 17+ and Maven 3.9+ are required; Maven downloads project dependencies automatically.';
    runCommand = 'mvn test';
  } else if (framework === 'selenium-python') {
    installCommand = 'pip install -r requirements.txt';
    runCommand = 'pytest tests/';
  }

  const readmeContent = `# AutoTest Architect - Automated Test Suite
**Feature:** ${ir.feature}
**Test Case ID:** ${ir.testCaseId}
**Framework:** ${framework}
**Sprint:** ${ir.sprint}
**Base Target URL:** ${ir.baseUrl}

---

## Getting Started

### 1. Install Dependencies
\`\`\`bash
${installCommand}
\`\`\`

### 2. Execute Tests
\`\`\`bash
${runCommand}
\`\`\`

### 3. Continuous Integration
This suite includes a pre-configured GitHub Actions workflow located at \`.github/workflows/test-automation.yml\`. Simply push this repository to GitHub to start automated CI test runs on every pull request.

---
*Auto-generated by AutoTest Architect Studio*
`;

  zip.file('README.md', readmeContent);

  // Generate blob and trigger browser download
  const blob = await zip.generateAsync({ type: 'blob' });
  const downloadUrl = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = downloadUrl;
  a.download = `${String(ir.testCaseId || 'test').toLowerCase().replace(/[^a-z0-9_-]+/g, '_')}_${framework}_suite.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.setTimeout(() => URL.revokeObjectURL(downloadUrl), 1000);
}
