import JSZip from 'jszip';
import { GeneratedCodeFile, FrameworkType, TestIR } from '../types/testAutomation';
import { generateCiPipeline } from './ciGenerators';

export async function exportSuiteAsZip(
  files: GeneratedCodeFile[],
  framework: FrameworkType,
  ir: TestIR
): Promise<void> {
  const zip = new JSZip();

  // Add the generated test and page object files
  files.forEach((file) => {
    zip.file(file.filepath, file.code);
  });

  // Include CI/CD pipeline inside the export package
  const ghWorkflow = generateCiPipeline('github-actions', framework, ir);
  zip.file(ghWorkflow.filepath, ghWorkflow.code);

  // Add a clean README.md explaining how to run
  let runCommand = 'npx playwright test';
  let installCommand = 'npm install && npx playwright install chromium';
  if (framework === 'playwright-python') {
    installCommand = 'pip install -r requirements.txt && playwright install';
    runCommand = 'pytest tests/';
  } else if (framework === 'selenium-java') {
    installCommand = 'mvn clean compile';
    runCommand = 'mvn test';
  } else if (framework === 'selenium-python') {
    installCommand = 'pip install selenium pytest webdriver-manager';
    runCommand = 'pytest tests/';
  }

  const readmeContent = `# AutoTest Architect - Automated Test Suite
**Feature:** ${ir.feature}
**Test Case ID:** ${ir.testCaseId}
**Framework:** ${framework}
**Sprint:** ${ir.sprint}
**Base Target URL:** ${ir.baseUrl}

---

## Getting Started

### 1. Install Dependencies
\`\`\`bash
${installCommand}
\`\`\`

### 2. Execute Tests
\`\`\`bash
${runCommand}
\`\`\`

### 3. Continuous Integration
This suite includes a pre-configured GitHub Actions workflow located at \`.github/workflows/test-automation.yml\`. Simply push this repository to GitHub to start automated CI test runs on every pull request.

---
*Auto-generated by AutoTest Architect Studio*
`;

  zip.file('README.md', readmeContent);

  // Generate package.json or requirements.txt if needed
  if (framework === 'playwright-ts' || framework === 'playwright-js') {
    const isTypeScript = framework === 'playwright-ts';
    const pkgJson = {
      ...(isTypeScript ? {} : { type: 'module' }),
      name: `${ir.feature.toLowerCase().replace(/[^a-z0-9]/g, '-')}-tests`,
      version: '1.0.0',
      private: true,
      scripts: {
        test: 'playwright test',
        'test:headed': 'playwright test --headed',
        'test:ui': 'playwright test --ui',
        report: 'playwright show-report'
      },
      devDependencies: {
        '@playwright/test': '^1.63.0',
        ...(isTypeScript ? { '@types/node': '^22.0.0', typescript: '^5.0.0' } : {})
      }
    };
    zip.file('package.json', JSON.stringify(pkgJson, null, 2));
  } else if (framework === 'playwright-python' || framework === 'selenium-python') {
    const reqTxt = framework === 'playwright-python'
      ? 'playwright>=1.44.0\npytest>=8.0.0\npytest-playwright>=0.5.0\n'
      : 'selenium>=4.20.0\npytest>=8.0.0\nwebdriver-manager>=4.0.0\n';
    zip.file('requirements.txt', reqTxt);
  }

  // Generate blob and trigger browser download
  const blob = await zip.generateAsync({ type: 'blob' });
  const downloadUrl = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = downloadUrl;
  a.download = `${ir.testCaseId.toLowerCase()}_${framework}_suite.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(downloadUrl);
}
